services:
  backend:
    image: fjeldberg/instarecipe-backend:latest
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      - PORT=9000

  frontend:
    image: fjeldberg/instarecipe-frontend:latest
    ports:
      - "9001:9001"
    env_file:
      - .env
    environment:
      - PORT=9001
       
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
   