name: Continuous Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            fjeldberg/instarecipe
          tags: |
            type=sha,format=short
            latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: fjeldberg/instarecipe-backend:latest
      
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: fjeldberg/instarecipe-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Copy docker-compose.yml to server
        run: |
          scp ./docker-compose.yml ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }}:~/instarecipe/

      - name: Copy .env to server
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} '
            cd ~/instarecipe
            rm .env
            touch .env
            echo "${{ secrets.SERVER_ENV }}" >> .env

      - name: Deploy to Server
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} '
            cd ~/instarecipe
            docker compose pull
            docker compose up -d
          '